Insert into Provider values (26969,'NVIDIA','West Virginia, USA');
Insert into provider values (45368,'CORSAIR','Atlanta, USA');
insert into provider values (31649,'PROTOCOL','Berlin, Alemania');
insert into provider values (68341,'CD PROJEKT RED','Florencia, Italia');
insert into provider values (31483,'ETIKA','Mallorca, España');
insert into provider values (21984,'CELERON','Venecia, Italia');
insert into provider values (12652,'DEVIANART','Buenos aires, Argentina');
insert into provider values (24560,'WILDCARD','Barcelona, España');
insert into provider values (87861,'OGILVY','Hong Kong, China');
insert into provider values (65507,'BLIZZARD','Los Angeles, USA');
insert into provider values (21377,'QWERTEE.COM','Moscu, Rusia');
insert into provider values (60767,'AMD','Tokyo, Japon');
insert into provider values (12591,'CLOAK','Santiago, Chile');
insert into provider values (23237,'OLYSEUM','Madrid, España');
insert into provider values (39200,'KOTCH','Bucaramanga, Colombia');
insert into provider values (59929,'LOGITECH','New York, USA');
insert into provider values (78313,'CLUTCH','Rio, Brasil');
insert into provider values (97373,'NINTENDO','Tokyo, Japon');
insert into provider values (81094,'ELECTRONIC ARTS','');
insert into provider values (74317,'RAZER','Bogota, Colombia');
insert into provider values (75730,'ALIENWARE','Paris, Francia');
insert into provider values (98645,'SIEMENS','Denver, Canada');
insert into provider values (18539,'INSOMNIAC','Quito, Ecuador');
insert into provider values (65935,'BETHESDA','Berlin, Alemania');
insert into provider values (28687,'MACHINIMA','Washington DC, USA');
insert into provider values (56748,'EASTER EGG','Edimburgo, Escocia');
insert into provider values (43252,'SONY','Glasgow, UK');
insert into provider values (73063,'SQUARE ENIX','Gran Bretaña, Inglaterra');
insert into provider values (40134,'RIOT GAMES','Los Angeles, USA');
insert into provider values (18902,'HYPERX','Washington DC');
insert into provider values (43251,'APPLE','Glasgow, UK');
insert into provider values (73062,'MICROSOFT','Gran Bretaña, Inglaterra');
insert into provider values (57748,'SAMSUNG','Edimburgo, Escocia');