Insert into Provider values (26969,'NVIDIA','West Virginia, USA',0);
Insert into provider values (45368,'CORSAIR','Atlanta, USA',0.00);
insert into provider values (31649,'PROTOCOL','Berlin, Alemania',0.00);
insert into provider values (68341,'CD PROJEKT RED','Florencia, Italia',0.00);
insert into provider values (31483,'ETIKA','Mallorca, España',0.00);
insert into provider values (21984,'CELERON','Venecia, Italia',0);
insert into provider values (12652,'DEVIANART','Buenos aires, Argentina',0);
insert into provider values (24560,'WILDCARD','Barcelona, España',0);
insert into provider values (87861,'OGILVY','Hong Kong, China',0);
insert into provider values (65507,'BLIZZARD','Los Angeles, USA',0);
insert into provider values (21377,'QWERTEE.COM','Moscu, Rusia',0);
insert into provider values (60767,'AMD','Tokyo, Japon',0);
insert into provider values (12591,'CLOAK','Santiago, Chile',0);
insert into provider values (23237,'OLYSEUM','Madrid, España',0);
insert into provider values (39200,'KOTCH','Bucaramanga, Colombia',0);
insert into provider values (59929,'LOGITECH','New York, USA',0);
insert into provider values (78313,'CLUTCH','Rio, Brasil',0);
insert into provider values (97373,'NINTENDO','Tokyo, Japon',0);
insert into provider values (81094,'ELECTRONIC ARTS','',0);
insert into provider values (74317,'RAZER','Bogota, Colombia',0);
insert into provider values (75730,'ALIENWARE','Paris, Francia',0);
insert into provider values (98645,'SIEMENS','Denver, Canada',0);
insert into provider values (18539,'INSOMNIAC','Quito, Ecuador',0);
insert into provider values (65935,'BETHESDA','Berlin, Alemania',0);
insert into provider values (28687,'MACHINIMA','Washington DC, USA',0);
insert into provider values (56748,'EASTER EGG','Edimburgo, Escocia',0);
insert into provider values (43252,'SONY','Glasgow, UK',0);
insert into provider values (73063,'SQUARE ENIX','Gran Bretaña, Inglaterra',0);
insert into provider values (40134,'RIOT GAMES','Los Angeles, USA',0);
insert into provider values (18902,'HYPERX','Washington DC',0);
insert into provider values (43251,'APPLE','Glasgow, UK',0);
insert into provider values (73062,'MICROSOFT','Gran Bretaña, Inglaterra',0);
insert into provider values (57748,'SAMSUNG','Edimburgo, Escocia',0);